### PR TITLE
Fix images for state data filter examples

### PR DESCRIPTION
**Pull request by tsurdilo**
Signed-off-by: Tihomir Surdilovic <tsurdilo@redhat.com>

**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ x] Specification
- [ ] Schema
- [ ] Examples
- [ ] Usecases
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:
Fixes images for state data filter section.

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by tsurdilo** [comment]
Fixes issues https://github.com/serverlessworkflow/specification/issues/168

**Review by sky132333 — APPROVED** [review]
good

**Comment by sky132333** [comment]
for example 1 maybe worng .
According to jsonpath：https://github.com/json-path/JsonPath
image

so example 1 result should be ：[ "apple", "orange", "pear" ].
You don't need an array outside。

**Comment by tsurdilo** [comment]
@singhkays i think the way it is now is correct. you can test with https://jsonpath.com/

**Pull request merged**
