### PR TITLE
Renamed EventRef Definition

### PR DESCRIPTION
**Pull request by cdavernas**
Renamed EventRef Definition's `resultEventTimeout` to `consumeEventTimeout`

**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [X] Specification
- [x] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:

The EventRef Definition's `resultEventTimeout` name is an artifact from the time the `consumeEventRef` was named `resultEventRef`. It therefore should be renamed as `consumeEventTimeout` for the sake of consistency.

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by antmendoza** [comment]
Hi @cdavernas 

the property `resultEventTimeout` is also present here https://github.com/serverlessworkflow/specification/blob/main/schema/workflow.json#L548

and here https://github.com/serverlessworkflow/specification/blob/main/specification.md?plain=1#L3991 twice, 

should we change it to `consumeEventTimeout` in those places too?

**Comment by tsurdilo** [comment]
ha good point! ty @antmendoza

**Review by tsurdilo — CHANGES_REQUESTED** [review]
please apply changes mentioned by Antonio :)

**Comment by cdavernas** [comment]
Fixed it, and fixed the `auth.json`. Can you, by the way, apply it to `0.8.x` as the schema def was invalid (bug)?

**Review by tsurdilo — APPROVED** [review]

**Pull request merged**
