### PR TITLE
Adding roadmap items from call 07/12/12

### PR DESCRIPTION
**Pull request by manuelstein**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ ] Specification
- [ ] Schema
- [ ] Examples
- [ ] Usecases
- [ ] Extensions
- [X] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:
We had a couple of new roadmap items in our [community call on 07/12/20](https://docs.google.com/document/d/1xwcsWQmMiRN24a7o7oy9MstzMroAup31oOkM5Dru1jQ/edit#). This PR adds them

Also, I believe the terminology has been discussed and is motivated in the [wiki terminology discussion](https://github.com/serverlessworkflow/specification/wiki/Terminology#control-perspective---state-vs-task-vs-step-vs-stage-vs-event-driven), so closing it

And eventually, the primer content sections that were completed have been moved to the wiki. The primer is an ever ongoing item (lots of potential topics), so keeping it for now.

**Special notes for reviewers**:
Happy to add links to issues as soon as they're written.

**Additional information (if needed):**

### CODE REVIEW

**Review by tsurdilo — APPROVED** [review]

**Comment by tsurdilo** [comment]
@manuelstein needs to rebases

**Review by ricardozanini — APPROVED** [review]

**Comment by tsurdilo** [comment]
yep. when you update pr after rebase make sure you add the "-s" flag when you do your commit

**Comment by tsurdilo** [comment]
@manuelstein i will merge this as soon as the signing thing is done. ty!

**Comment by manuelstein** [comment]
Tidied up and signed

**Pull request merged**
