### PR TITLE
Fix typo RunWokflow

### PR DESCRIPTION
**Pull request by zolero**
Fixes typo in Specification

Description:
This pull request fixes a typo in the specification document, correcting "RunWokflow" to "RunWorkflow."

Changes Made:
Corrected the typo "RunWokflow" to "RunWorkflow" in the specification document.

### CODE REVIEW

**Comment by cdavernas** [comment]
@zolero Thanks for your PR ❤️ 
Sorry for being a PITA, but could you describe the PR using the template, for bookkeeping purpose? I know it's just a typo fix, but we future users might not have the patience to check changes, and would therefore benefit from a short description 😉 
Furthermore, could you be so kind to sign-off your commit?

**Comment by zolero** [comment]
> @zolero Thanks for your PR ❤️ Sorry for being a PITA, but could you describe the PR using the template, for bookkeeping purpose? I know it's just a typo fix, but future users might not have the patience to check changes, and would therefore benefit from a short description 😉 Furthermore, could you be so kind to sign-off your commit?

Will follow the template next time as well the signoff commit messages. Didn't know. I'll take it for granted! Someone could apply it to it's next PR.

**Review by cdavernas — APPROVED** [review]
LGTM, cheers ❤️

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@zolero can you please rebase it?

**Comment by ricardozanini** [comment]
Nevermind, I did it already.

**Pull request merged**
