### PR TITLE
add required usedForCompensation for subflowstate (branch 0.6.x)

### PR DESCRIPTION
**Pull request by antmendoza**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ ] Specification
- [X] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:
add required usedForCompensation for subflowstate, 

[in the previous PR](https://github.com/serverlessworkflow/specification/pull/405) I cherry-picked the commit from the main branch but subflowstate is not part of the specification on 0.7 version.

Added here required usedForCompensation for subflowstate

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Review by tsurdilo — APPROVED** [review]

**Comment by tsurdilo** [comment]
will update website shortly

**Comment by antmendoza** [comment]
Hi @tsurdilo is there anything I can do? 

do you want me to create a RP for the website ?

**Comment by tsurdilo** [comment]
@antmendoza oops :) give me 30 mins ill push it. sorry.

**Comment by antmendoza** [comment]
No problem @tsurdilo , I don't need it to be in the website, Just wanted to help

**Pull request merged**
