### PR TITLE
Moves functionref to its own definition

### PR DESCRIPTION
**Pull request by tsurdilo**
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>

**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ ] Specification
- [ x] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by tsurdilo** [comment]
@manuelstein i know we didnt get to this in meet but it does not introduce any changes to the spec. just moves a definition from being in-line to the schema definitions . i think its safe to just add it to unblock sdk-typescript guys.

**Comment by Booster2ooo** [comment]
Could this be merged in 0.6.x please?

**Comment by JBBianchi** [comment]
Could this also be merged into 0.6.x please?

**Comment by tsurdilo** [comment]
@JBBianchi yes, I will cherry-pick it now

**Pull request merged**
