### PR TITLE
Fix small typo in `resultEventTimeout` description

### PR DESCRIPTION
**Pull request by spolti**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts of this PR update:**

- [ ] Specification
- [ ] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [x] Other

**Discussion or Issue link**:

**What this PR does / why we need it**:

**Special notes for reviewers**:

**Additional information:**

### CODE REVIEW

**Review by cdavernas — APPROVED** [review]

**Review by antmendoza — APPROVED** [review]

**Comment by ricardozanini** [comment]
Hi! Can you please try changing it in the main branch? You opened a PR to the 0.8.x branch.

**Comment by spolti** [comment]
seems that main branch does not have these changes yet.

**Comment by spolti** [comment]
these changes I mean, the v08 additions.

**Comment by ricardozanini** [comment]
I see. That's fine to change small typos in the current version thou.

**Review by ricardozanini — APPROVED** [review]

**Comment by spolti** [comment]
I can cherry pick these commits to main if needed.

**Review by tsurdilo — APPROVED** [review]

**Review by tsurdilo — CHANGES_REQUESTED** [review]
Please do pr against main branch. ty

**Comment by spolti** [comment]
@tsurdilo seems that the main branch is not updated yet with the v08 additions.

**Comment by spolti** [comment]
@tsurdilo what am I saying is that on the main branch, the content I updated, does not exists.

**Comment by ricardozanini** [comment]
@spolti as we talked in the meeting, this content is not valid in main since we deprecated this attribute.

**Comment by tsurdilo** [comment]
thanks for clarifying

**Pull request merged**
