### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by yzhao244**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [x] Specification
- [ ] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:
Fix minor typos in specification.md
**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Review by tsurdilo — APPROVED** [review]

**Comment by tsurdilo** [comment]
Nice! Thank you @yzhao244

**Review by cdavernas — APPROVED** [review]
Thank you @yzhao244 !!!

**Comment by yzhao244** [comment]
@tsurdilo I followed the instructions from the following DCO details link. However, the DCO check still failed :(
(https://github.com/serverlessworkflow/specification/pull/390/checks?check_run_id=2668355843)

**Comment by ricardozanini** [comment]
Can you please sign your commit?

> git commit --amend --no-edit --signoff
> git push --force-with-lease origin typo-fix

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
> @tsurdilo I followed the instructions from the following DCO details link. However, the DCO check still failed :(
> (https://github.com/serverlessworkflow/specification/pull/390/checks?check_run_id=2668355843)

Your commit is not signed :(

**Comment by cdavernas** [comment]
Yeah I'm not sure how it works, but I usually get problems, too. Added autosign feature to VisualStudio, it does use my GPG key, but DCO systematically fails if not using bash to signoff

**Pull request merged**
