### PR TITLE
Improve state execution timeouts

### PR DESCRIPTION
**Pull request by tsurdilo**
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>

**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ x] Specification
- [x ] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:
* Improves state execution timeout property:
  - Adds ability to set "single" and "total" properties meaning that you can define the max execution timeout per state execution excluding / including retries.
  
**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@cdavernas @manuelstein @ricardozanini  let me know if this raises any questions.

**Review by ricardozanini — APPROVED** [review]

**Comment by cdavernas** [comment]
@tsurdilo I'm off until Friday, will review it in detail and bring some comments of our DM discussions along with it asap ;)

**Comment by tsurdilo** [comment]
@cdavernas sounds good

**Comment by tsurdilo** [comment]
rebased

**Pull request merged**
