### PR TITLE
OData function

### PR DESCRIPTION
**Pull request by cdavernas**
Signed-off-by: charles.davernas <charles.davernas@neuroglia.io>

**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [x] Specification
- [x] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:

Adds OData support to Functions

### CODE REVIEW

**Review by ricardozanini — COMMENTED** [review]
The PR seems fine. I need to go through to OData documentation to get it right. I haven't seen it around too much. I'm wondering if it's a possibility to add this function type as an optional implementation.

**Comment by cdavernas** [comment]
@ricardozanini OData is an aternative to GraphQL, and inversly. Though GraphQL does seem more popular lately, the adoption of OData has been well proven, and is supported by al lot of products out there.

Furthermore, considering I am only suggesting to support queries, this should be easier to implement than GraphQL. Basically, it's just a GET request with some query params ($filter, $top, $skip, ...)

**Comment by ricardozanini** [comment]
Thanks for clarifying, @cdavernas 

I understand that OData might be getting popular, but my concern is broader (not to this particular expression). Implementations might not need to add support to every expression we suggest in the spec. We might need to draw a line where an engine/runtime is considered an implementation (for instance, just `jq` expression support is considered ok?). Just a suggestion, we might need to add that to the spec and/or resolve in the TCK. :thinking:

**Comment by tsurdilo** [comment]
@ricardozanini Yeah we can look into that but not sure it's a big issue tbh.
It's never been a "issue" that most bpmn engines support a subset of the executable subset that the bpmn spec defines. They just say they support bpmn.


We can also define compliance subset but i don't think its a defining factor in the end of runtimes declaring support for the dsl.

**Comment by ricardozanini** [comment]
> @ricardozanini Yeah we can look into that but not sure it's a big issue tbh.

Yeah, I agree! It was just something that slipped into my head when I was reviewing this PR. I'll add it to the backburner for now.

**Review by ricardozanini — APPROVED** [review]

**Comment by tsurdilo** [comment]
@cdavernas lgtm - only thing to think about is if possible to integrate the odata schema so can be used by vscode plugin as well. We can think about it for future.

**Review by tsurdilo — APPROVED** [review]

**Comment by cdavernas** [comment]
@tsurdilo I guess it's doable, I'll try to look into it 😉

**Comment by tsurdilo** [comment]
@cdavernas 
I tried rebasing from your local branch but it gives me 403 (access denied) - can you 
1. rebase pr
2. update roadman/README.md

I'll merge right after

**Comment by tsurdilo** [comment]
Replaced with https://github.com/serverlessworkflow/specification/pull/433
Closing this one

**Pull request closed without merging**
