### PR TITLE
Fixed examples hydration breaking samples in README

### PR DESCRIPTION
**Pull request by JBBianchi**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts of this PR update:**

- [ ] Specification
- [ ] Schema
- [x] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**Discussion or Issue link**:

#822

**What this PR does / why we need it**:

It **should** fix the samples in the examples README.

**Special notes for reviewers**:

**Additional information:**

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
Can you sign your commit? 😬

**Comment by JBBianchi** [comment]
> Can you sign your commit? 😬

I tried to amend but it looks like I failed yet again. I'll delete this branch and redo the PR sorry :/

**Comment by ricardozanini** [comment]
@JBBianchi usually I amend and `push -f`

**Review by cdavernas — APPROVED** [review]

**Comment by JBBianchi** [comment]
I managed after some brawling against git 💪

**Pull request merged**
