### PR TITLE
Fix required params def for usedForCompensation

### PR DESCRIPTION
**Pull request by tsurdilo**
Signed-off-by: Tihomir Surdilovic <tihomir@temporal.io>

**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ ] Specification
- [x ] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:
Fix for the required param definition of usedForCompensation

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by JBBianchi** [comment]
Why use `"enum": [ false ]` instead of `"const": false` like it was with the "positive" version?

**Review by ricardozanini — APPROVED** [review]

**Comment by tsurdilo** [comment]
@JBBianchi my impression was that this was causing the issue in sdk. If not we can just close this. Either approach work it seems.

**Comment by JBBianchi** [comment]
I'm not sure you're fixing the issue. The goal is to avoid "falling into" `then` if `usedForCompensation` is not set.

Here, you did just changed the expression of the `if`, meaning that you said `if (!false) ...` instead of `if(true) ...`, which doesn't change a lot in the end. If `usedForCompensation` is not set, if will be ignored and it will fall into `then` anyways.

Either you have to change the if/then/else to invert the logic (`if (false) ...`) which means interverting then and else as well, or you can add a constrain to if with a require on `usedForCompensation` .

**Comment by tsurdilo** [comment]
@JBBianchi i am testing this inside VSCode but they might have a different parsing approach for this.
We cannot make "usedForCompensation" a required field unfortunately.

**Comment by JBBianchi** [comment]
> 
> 
> @JBBianchi i am testing this inside VSCode but they might have a different parsing approach for this.
> We cannot make "usedForCompensation" a required field unfortunately.

In the if block:
```json
      "if": {
        "properties": {
          "usedForCompensation": {
            "const": true
          }
        },
        "required": ["usedForCompensation"]
      }
```

**Comment by JBBianchi** [comment]
> 
> 
> @JBBianchi i am testing this inside VSCode but they might have a different parsing approach for this.
> We cannot make "usedForCompensation" a required field unfortunately.
> OK I'll revert the logic then as suggested.

Btw, from my understanding, it is "kind of" required as it has a default value of "false"... isn't it?

**Comment by tsurdilo** [comment]
@JBBianchi updated let me know if this works now

**Comment by JBBianchi** [comment]
> 
> 
> @JBBianchi updated let me know if this works now

I tried with the sample provided in the [related SDK issue](https://github.com/serverlessworkflow/sdk-typescript/issues/99).
The workflow is not valid until we add an `end` property for instance. I think that's what we wanted?

```typescript
import { DefinedError } from 'ajv';
import { WorkflowValidator, Specification } from '../src';

describe('missing usedForCompensation', () => {
  it('should be invalid', () => {
    const workflow: Specification.Workflow = {
      id: 'helloworld',
      version: '1.0',
      name: 'Hello World Workflow',
      description: 'Inject Hello World',
      start: 'Hello State',
      states: [
        {
          type: 'inject',
          name: 'Hello State',
          data: {
            result: "Hello World!"
          }
        } as Specification.Injectstate
      ]
    };
    const workflowValidator: WorkflowValidator = new WorkflowValidator(workflow);
    const isValid = workflowValidator.validate();
    if (!isValid) {
      workflowValidator.errors.forEach((error: DefinedError) => console.error(error.message));
    }
    expect(isValid).toBe(false);
  });
});
```

outputs:
```
must have required property 'timeDelay'
must have required property 'timeDelay'
must match exactly one schema in oneOf
must have required property 'onEvents'
must have required property 'onEvents'
must have required property 'onEvents'
must match exactly one schema in oneOf
must have required property 'actions'
must have required property 'actions'
must have required property 'actions'
must match exactly one schema in oneOf
must have required property 'branches'
must have required property 'branches'
must have required property 'branches'
must match exactly one schema in oneOf
must have required property 'dataConditions'
must have required property 'eventConditions'
must match exactly one schema in oneOf
must have required property 'workflowId'
must have required property 'workflowId'
must match exactly one schema in oneOf
must have required property 'end'                      <----
must have required property 'transition'
must match exactly one schema in oneOf
must have required property 'inputCollection'
must have required property 'inputCollection'
must have required property 'inputCollection'
must have required property 'inputCollection'
must match exactly one schema in oneOf
must have required property 'action'
must have required property 'action'
must match exactly one schema in oneOf
must match a schema in anyOf
```

and is compliant to the test (workflow is invalid).

By adding `end: true` to the Injectstate, the workflow becomes valid.

**Comment by tsurdilo** [comment]
@JBBianchi yeah this seems correct now - if usedForCompensation is not defined you need either "end" or "transition" defined.

One question regarding the above validation output - it seems it pulls in validation of all the states, not just inject state which is defined.

**Comment by JBBianchi** [comment]
> 
> 
> @JBBianchi yeah this seems correct now - if usedForCompensation is not defined you need either "end" or "transition" defined.
> 
> One question regarding the above validation output - it seems it pulls in validation of all the states, not just inject state which is defined.

Yes, it validates the `states` property against all the union types even if the `type` property of each one of them is a const and it should be able to filter it down to `injectstate`. That might be something to improve on [ajv ](https://ajv.js.org/) side, not sure...

**Comment by tsurdilo** [comment]
@JBBianchi ok thats fair, we can take a look at that at some point. 
@JBBianchi @antmendoza I'll go ahead and merge this then as its a fix - do you guys need this in 0.6.x as well ?

**Comment by JBBianchi** [comment]
> 
> 
> @JBBianchi ok thats fair, we can take a look at that at some point.
> @JBBianchi @antmendoza I'll go ahead and merge this then as its a fix - do you guys need this in 0.6.x as well ?

Preferably <3

**Comment by antmendoza** [comment]
late to the party, thank you @tsurdilo @JBBianchi ;)

**Comment by antmendoza** [comment]
@tsurdilo are you going to release a new version of the 0.6 as well ?

**Comment by tsurdilo** [comment]
@antmendoza thats a good question :) idk the answer now honestly, let's discuss. 
From your perspective, is it needed for the typescript sdk?

**Comment by antmendoza** [comment]
If it is an inconvenience we can life without it

the actual implementation is fetching the json schemas from https://api.github.com/repos/serverlessworkflow/specification/contents/schema?ref=v0.6 but we can just copy them

**Comment by tsurdilo** [comment]
@antmendoza is it possible that you pull the schema from https://serverlessworkflow.io/schemas/0.6/workflow.json ?
it would be much easier for me to push the 0.6.x updates we make there than cut a whole new release. let me know

**Comment by JBBianchi** [comment]
> 
> 
> @antmendoza is it possible that you pull the schema from https://serverlessworkflow.io/schemas/0.6/workflow.json ?
> it would be much easier for me to push the 0.6.x updates we make there than cut a whole new release. let me know

Atm it's using the GitHub API to list and download everything from `schema` of the specified `ref` (pending PR changes the defaut ref from v{version} to {version}.x).

It's not a big deal to change and get the schemas from `https://serverlessworkflow.io/schemas/0.6/workflow.json` (only unreferenced schemas like extensions/kpi.json won't be fetched as there is no pointer to it for instance, once again, no big deal).

One thing thought, it would be nice to fix the schemas `$id` because right now it's ...serverlessworkflow.org/~~core~~/0.6/workflow.json

**Comment by tsurdilo** [comment]
> One thing thought, it would be nice to fix the schemas `$id` because right now it's ...serverlessworkflow.org/~core~/0.6/workflow.json

@JBBianchi what should we change it to ?

**Comment by JBBianchi** [comment]
I think the [$id](https://github.com/serverlessworkflow/specification/blob/0.6.x/schema/workflow.json#L2) should be `"$id": "https://serverlessworkflow.io/schemas/0.6/workflow.json"` so it's a valid URL.

**Comment by tsurdilo** [comment]
> I think the [$id](https://github.com/serverlessworkflow/specification/blob/0.6.x/schema/workflow.json#L2) should be `"$id": "https://serverlessworkflow.io/schemas/0.6/workflow.json"` so it's a valid URL.

+1 will update over weekend

**Comment by tsurdilo** [comment]
@JBBianchi 
https://github.com/serverlessworkflow/specification/pull/387 (master)
https://github.com/serverlessworkflow/specification/pull/388 (0.6.x)

I already updated this on the website by the way :)

**Review by manuelstein — APPROVED** [review]

**Comment by tsurdilo** [comment]
@JBBianchi https://github.com/serverlessworkflow/serverlessworkflow.github.io/commit/aad78c58d1ccbe5299b636628f6f37dd530ce09d

**Pull request merged**
