### PR TITLE
rename workflowextensions.json to extensions.json

### PR DESCRIPTION
**Pull request by antmendoza**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts of this PR update:**

- [ ] Specification
- [x] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**Discussion or Issue link**:

**What this PR does / why we need it**:

**Special notes for reviewers**:

**Additional information:**

### CODE REVIEW

**Review by tsurdilo — APPROVED** [review]

**Review by cdavernas — CHANGES_REQUESTED** [review]
Why that PR? I know it's minor, but there is no discussion/issue or even proper description. Is there a problem with the file name as is?

**Comment by tsurdilo** [comment]
my understanding is that we are trying to fix the editor on website cause its broken. im sure antonio will add a desription..

**Comment by cdavernas** [comment]
Allright, cheers! Btw, shouldn't we instead fix the website so that we can keep the orignal file name? 
Again, no biggest, but extensions.json is less verbose and follows naming conventions of all files. 
Or is that fix "temporary", meaning for current version only?

**Comment by antmendoza** [comment]
@cdavernas appologies, 

Shouldn't the id value be the same as the filename?

**Comment by antmendoza** [comment]
@cdavernas  `extensions.json` make sense to me

**Comment by cdavernas** [comment]
@antmendoza ahah no worries, even less coming from you ❤️

**Comment by antmendoza** [comment]
ok, I am renaming the filename, I will wait for @tsurdilo  and @ricardozanini  confirmation.

**Comment by ricardozanini** [comment]
+1 to keep `extensions.json`.

**Comment by antmendoza** [comment]
done :)

**Review by cdavernas — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
