### PR TITLE
Remove oneOf condition duplicated

### PR DESCRIPTION
**Pull request by antmendoza**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ ] Specification
- [x] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:
Remove oneOf condition duplicated 

For some reason the library we are using in the sdk-typescript to validate agains the json schema is complaining because this duplications. 

cc @JBBianchi 
 
**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@antmendoza weird cause it seems its not a duplication :( 
For example:

```json
"oneOf": [
          {
            "required": [
              "name",
              "type",
              "branches",
              "end"
            ]
          },
          {
            "required": [
              "name",
              "type",
              "branches",
              "transition"
            ]
          }
        ]
```
is needed as this state can have either a transition or an end definition , but not both.

what errors are you getting in your tool? maybe we can try to change this somehow so it works with it instead of removing?
wdyt?

**Comment by antmendoza** [comment]
Hi @tsurdilo 

I see duplications in the json schemas, 0.6 version https://github.com/serverlessworkflow/specification/blob/0.6.x/schema/workflow.json#L577 


If you extend up the file viewer you will see something like this 

Screenshot 2021-05-16 at 20 19 25

**Comment by antmendoza** [comment]
those duplications are not in the main branch, btw

**Comment by tsurdilo** [comment]
@antmendoza sorry i am blind :) didnt see this was against 0.6.x :) My bad

**Review by tsurdilo — APPROVED** [review]

**Comment by antmendoza** [comment]
no problem, thank you!! :)

**Comment by tsurdilo** [comment]
Nice fix! No need to go over it in meet as it fixes 0.6.x current error, no updates to spec. will merge

**Pull request merged**
