### PR TITLE
fix(*): update auth struct type to array or object

### PR DESCRIPTION
**Pull request by lsytj0413**
Signed-off-by: lsytj0413 <511121939@qq.com>

**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts of this PR update:**

- [x] Other

**Discussion or Issue link**:

**What this PR does / why we need it**:

- According to the examples, the Auth field't type should be array or object, not array or string

**Special notes for reviewers**:

**Additional information:**

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Review by cdavernas — CHANGES_REQUESTED** [review]
No, the `auth` should indeed be of `array` or `string` types, I don't know which examples you are speaking about.

In the case `auth` is `string`, it is considered as a reference to an external definition of the `array` (ex: https://test.com/mysharedauth)

**Comment by ricardozanini** [comment]
@lsytj0413, @cdavernas is right. The string, in this case, is an external reference. Can you please point out the examples you saw the error?

**Comment by lsytj0413** [comment]
> @lsytj0413 No, the top level `auth` property should indeed be of `array` or `string` types, I don't know which examples you are speaking about, which would be where the error(s) is/are.
> 
> In the case `auth` is `string`, it is considered as a reference to an external definition of the `array` (ex: https://test.com/mysharedauth)

I have seen [this example](https://github.com/serverlessworkflow/specification/pull/667#pullrequestreview-1097807409) in sdk-go implement and it should validate with no error.

So, this should be an bug in sdk-go?

**Comment by tsurdilo** [comment]
> I have seen [this example](https://github.com/serverlessworkflow/sdk-go/blob/main/parser/testdata/workflows/applicationrequest.json#L8) in sdk-go implement and it should validate with no error.

nice catch, i think the sample in go sdk should be updated

**Comment by lsytj0413** [comment]
Ok，If we confirm it's an bug in sdk-go，i would like to fix it.

**Comment by ricardozanini** [comment]
The SDK is implementing version 0.7 of the spec. Thanks for the PR; I've pushed it to the 0.8 milestone! :)

**Pull request closed without merging**
