### PR TITLE
Exclude unsupported States from timeouts.

### PR DESCRIPTION
**Pull request by hasys**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts of this PR update:**

- [X] Specification
- [ ] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**Discussion or Issue link**:
PR clarifies which states can use Timeouts based on this conversation: https://github.com/serverlessworkflow/specification/discussions/726

**What this PR does / why we need it**:

**Special notes for reviewers**:

**Additional information:**

### CODE REVIEW

**Comment by ricardozanini** [comment]
@hasys can you please sign the commit?

Another thing is, do the  `Sleep` and `Inject` state sessions/scheme has the timeout property defined/explained too? Can you please also review those?

Thanks!

**Comment by hasys** [comment]
Hello @ricardozanini,

sorry for the delay, commit is signed and Sleep/Inject states doesn't have timeouts in their specification which is correct.

Thank you!

**Review by cdavernas — APPROVED** [review]
LGTM!

**Review by tsurdilo — APPROVED** [review]

**Comment by tsurdilo** [comment]
@cdavernas @ricardozanini merging. thanks

**Pull request merged**
