### PR TITLE
fix(*): remove key property of workflow

### PR DESCRIPTION
**Pull request by lsytj0413**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts of this PR update:**

- [x] Specification

**Discussion or Issue link**:

**What this PR does / why we need it**:

Fixed https://github.com/serverlessworkflow/specification/issues/742

**Special notes for reviewers**:

**Additional information:**

### CODE REVIEW

**Comment by cdavernas** [comment]
@lsytj0413  Adding the blocked status because, as discussed in related issue, the `key` property is used to compute a runtime defined key of instances of the definition. 
IMHO, removing the mutual exclusiveness of id and key should be the object of the PR, not the removal of a (personally) critical field

**Review by cdavernas — CHANGES_REQUESTED** [review]
As per comment, please re-add the key property, or drop that PR altogether.
As a rule of thumb, you should first have the go ahead from maintainers in a discussion or issue before doing a PR, that would save you the time invested, which I however thank you for 🥰

**Comment by lsytj0413** [comment]
/close

waiting for community's decision.

**Pull request closed without merging**
