### PR TITLE
Support URIs with interpolation

### LINKED ISSUE #878: Fix `endpoint` URI format in workflow SCHEMA
**What seems off**:
The Workflow Schema uses the `uri` format in the `endpoint` property. This format is not valid for template URI like `https://petstore.swagger.io/v2/pet/{petId}`

**What you expected to be**:
That either URI and URI template passes the schema tests. See https://json-schema.org/understanding-json-schema/reference/string#resource-identifiers

**Anything else we need to know?**:
See GHA failure from #865 PR.

**Environment**:

- Specification version used:
1.0.0-alpha1

### PR DESCRIPTION
**Pull request by matthias-pichler-warrify**
Signed-off-by: Matthias Pichler <m.pichler@warrify.com>

**Please specify parts of this PR update:**

- [ ] Specification
- [x] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Use Cases
- [ ] Community
- [ ] CTK
- [ ] Other

**Discussion or Issue link**:

Closes #878 

**What this PR does**:

I added a custom `uri` definition that uses the Regex from the URI RFC to validate usi and therefore allows curly braces `{}`

**Additional information:**

I replaced all occurences of uri ... even those for event listers, externalResources etc ... is that desired?

### CODE REVIEW

**Comment by cdavernas** [comment]
> I replaced all occurences of uri ... even those for event listers, externalResources etc ... is that desired?

Yes, you rule! Thank you!

**Comment by matthias-pichler-warrify** [comment]
I saw: https://github.com/serverlessworkflow/specification/pull/869 use `format: uri-template` which I didn't even know existed but seems more correct?

**Comment by ricardozanini** [comment]
@cdavernas I don't think that's desired. JSON Schema already has the `uri-template` format that we can leverage, so only the `endpoint` attribute requires that the URI has a template, not all of them. I went through each URI field and I believe only that one is a valid template one?

Also, `uri-template` also validates `uri`.

**Comment by ricardozanini** [comment]
> I saw: #869 use `format: uri-template` which I didn't even know existed but seems more correct?

That's #879 

The idea is to use `format: uri` for fixed URIs and `format: uri-template` for the ones we need templating, so leveraging directly from the RFC instead of bringing the regex it's safer IMO.

**Comment by matthias-pichler-warrify** [comment]
> @cdavernas I don't think that's desired. JSON Schema already has the `uri-template` format that we can leverage, so only the `endpoint` attribute requires that the URI has a template, not all of them. I went through each URI field and I believe only that one is a valid template one?
> 
> Also, `uri-template` also validates `uri`.

Jap I am going to close this in favor of #879

**Pull request closed without merging**
