### PR TITLE
Example Fix: Add state definition hyperlinks to examples

### PR DESCRIPTION
**Pull request by yzhao244**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ ] Specification
- [ ] Schema
- [x] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:
Adds hyperlinks of state definition to some examples to be consistent and easy to navigate since Inject State example has hyperlink already.
**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Review by tsurdilo — APPROVED** [review]

**Comment by tsurdilo** [comment]
@yzhao244 
Thank you for the PR! The DCO check is failing because your commit is not signed. You can find more info on this here: https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work for example.

If it's not too much effort please try to sign it. If not, we can merge it this time np.

**Comment by yzhao244** [comment]
@tsurdilo just signed my commit. Thanks :)

**Comment by tsurdilo** [comment]
no need imo to discuss in meeting. adds nice links to the examples doc. thanks again for the contribution!

**Comment by yzhao244** [comment]
@tsurdilo You are welcome. I like this project and that's what I am here for !!! Contributing :)

**Pull request merged**
