### PR TITLE
Specify task and workflow arguments

### LINKED ISSUE #951: Document content of $workflow and $task arguments
**What would you like to be added**:

The `$workflow` and `$task` arguments are mentioned in the DSL but their contents are never specified. We should clarify this:

## `$workflow`

- `$workflow.definition` ... the workflow definition as a parsed object
- `$workflow.input` ... the input of the workflow _BEFORE_ the `input.from` expression was applied. For the result of the `input.from` expression use the `$input` argument
- `$workflow.startedAt`... an object with the properties `iso8601`, `epochMillis` and `epochNanos` to represent the execution start time
- `$workflow.id` ... the unique id of the execution

## `$task`

- `$task.definition` ... the task definition (object under the name) as a parsed object
- `$task.input` ... the input of the workflow _BEFORE_ the `input.from` expression was applied. For the result of the `input.from` expression use the context `.` of the expression
- `$task.startedAt`... an object with the properties `iso8601`, `epochMillis` and `epochNanos` to represent the task start time
- `$task.name` ... the unique name of the task

**Why is this needed**:

**Open Questions**:

Should the `.input` properties be the result of the `input.from` expression or the raw input to avoid duplication?

### PR DESCRIPTION
**Pull request by matthias-pichler-warrify**
Signed-off-by: Matthias Pichler <m.pichler@warrify.com>

**Please specify parts of this PR update:**

- [x] Specification
- [ ] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Use Cases
- [ ] Community
- [ ] CTK
- [ ] Other

**Discussion or Issue link**:

Closes #951

**What this PR does**:

It clarifies the contents of the `$workflow` and `$task` arguments

**Additional information:**

### CODE REVIEW

**Review by cdavernas — APPROVED** [review]
You are on fire man! LGTM! Thanks ❤️

**Comment by matthias-pichler-warrify** [comment]
@cdavernas @ricardozanini @fjtirado should `$task.input` and `$workflow.input` contain the raw input before `input.from` is applied? This would justify their existence but would make then somewhat inconsistent with other uses of the word "input" (which usually refers to the filtered input).

should we use `$task.rawInput` and `$workflow.rawInput` instead?

**Comment by JBBianchi** [comment]
> should $task.input and $workflow.input contain the raw input before input.from is applied? 

That's my understanding indeed.

> should we use $task.rawInput and $workflow.rawInput instead?

I'm not against, it can bring some more clarity.

**Comment by fjtirado** [comment]
@matthias-pichler-warrify  Hmmm, I understand workflow.input and task.input in an intuitive way, so Im not in favour of adding raw prefix to them
I like the PR as it is ;)

**Review by fjtirado — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
