### PR TITLE
Temporal comparisons examples

### PR DESCRIPTION
**Pull request by tsurdilo**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ ] Specification
- [ ] Schema
- [ x] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:
Provides comparison examples with Temporal workflow
**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by tsurdilo** [comment]
easier to read parsed markdown: https://github.com/tsurdilo/specification/blob/temporalcomparison/examples/examples-temporal.md

**Comment by tsurdilo** [comment]
depends on https://github.com/serverlessworkflow/specification/pull/223

**Review by ricardozanini — APPROVED** [review]
Seems fine to me. I assume we took these examples from their repo, so should work if someone else copies and pastes these snippets. 

Do you think it's worth adding the version of the Temporal project? If something changes in there, at least our examples will be valid for the given version. Since it should be hard to keep up to date with their API/code changes for each released version.

**Comment by tsurdilo** [comment]
@ricardozanini yeah each example has that "Full Temporal Example" link going back to the source file in https://github.com/temporalio/samples-java. They also have Go examples but this was just easier for me.

**Comment by tsurdilo** [comment]
@ricardozanini added the current latest release so ppl can reference. hope thats better now

**Review by jorgenj — APPROVED** [review]

**Review by ricardozanini — APPROVED** [review]

**Comment by tsurdilo** [comment]
@ricardozanini @jorgenj thanks for review guys! Will merge after we resolve https://github.com/serverlessworkflow/specification/pull/223

**Comment by tsurdilo** [comment]
removed the depends to https://github.com/serverlessworkflow/specification/pull/223
we can merge

**Pull request merged**
