### PR TITLE
Add Schema Validation and Examples to CI

### LINKED ISSUE #794: Bug in `functions` schema
**What seems off**:

The `functions` key isn't nested inside `properties` here:
https://github.com/serverlessworkflow/specification/blob/8a7152e0931a5f41a1c4abaf344d7ce1fd92410f/schema/functions.json#L6

I think it is meant to be?

**What you expected to be**:

Nested inside `properties`.

**Anything else we need to know?**:

It might be a good idea to run all the schemas through a strict validator. ajv's strict mode would fit the bill, it reports:

```
Error: strict mode: unknown keyword: "functions" 
```

**Environment**:

- Specification version used:

### PR DESCRIPTION
**Pull request by ricardozanini**
**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts of this PR update:**

- [ ] Specification
- [x] Schema
- [x] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**Discussion or Issue link**:

#794 

**What this PR does / why we need it**:

- Add all the examples from [examples/README.md]() file to separate files, so external tooling can now import them and run for tests
- Add a Node.js application to verify our schemas against those examples
- Add a GitHub Action to run in every PR to verify if the examples are valid to the Schemas

Open a new PR:
- Add the `properties` field to each separate definition so we enable single validation. For example, `functions.json` should be able to serve as a single schema definition.

**Special notes for reviewers**:
@JBBianchi After merging this one, we can then add the git post-hook to have an updated README file.

**Additional information:**
Now we have an application to maintain :)
I'm not a Node.js/Typescript specialist, so if there's something to improve, please let me know in the review.

### CODE REVIEW

**Comment by ricardozanini** [comment]
@JBBianchi So I can expect a PR soon coming here upgrading this code base + post-hook/templating README? :D

**Comment by JBBianchi** [comment]
> @JBBianchi So I can expect a PR soon coming here upgrading this code base + post-hook/templating README? :D

Yes, with pleasure, I'll do as soon as than one is merged.

**Comment by ricardozanini** [comment]
@cdavernas can you take a look? I'll open a second PR to actually solve #794.

**Comment by ricardozanini** [comment]
Has been two weeks since the introduction of this PR and we have two votes for merging. I think we can go ahead @cdavernas

**Comment by cdavernas** [comment]
@ricardozanini Agreed, as per code of conduct.

**Comment by cdavernas** [comment]
I guess you can add your own review then merge

**Pull request merged**
