### PR TITLE
#461 Make start param optional

### PR DESCRIPTION
**Pull request by manick02**
Signed-off-by: cb-manick <manickavasagam.sundaram@gmail.com>

**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ ] Specification
- [x] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Review by ricardozanini — COMMENTED** [review]
LGMT! Have you gone through the [specification.md](https://github.com/serverlessworkflow/specification/blob/main/specification.md) file to see if there's any mention about `start` being a required attribute?

**Comment by manick02** [comment]
> LGMT! Have you gone through the [specification.md](https://github.com/serverlessworkflow/specification/blob/main/specification.md) file to see if there's any mention about `start` being a required attribute?

Let me go through them in detail and come back

**Comment by manick02** [comment]
@tsurdilo thanks for the pointers. I am in the IST timezone, anytime between 6 PM - 9 PM IST would be convenient for the sync up. I will ping you in slack

**Comment by tsurdilo** [comment]
@manick02 sorry i havent been able to look at this yet. will directly update this pr with proposed text updates for spec and have you review it. hope that's ok. will do this asap

**Review by cdavernas — APPROVED** [review]
LGTM! Thanks!

**Comment by manick02** [comment]
> @manick02 sorry i havent been able to look at this yet. will directly update this pr with proposed text updates for spec and have you review it. hope that's ok. will do this asap

Absolutely fine, I am trying to understand and get more details meanwhile

**Comment by tsurdilo** [comment]
@manick02 updated text, roadmap and rebased against master

@cdavernas @ricardozanini 
the only reasonable way for start to be optional is to say if its not defined the very first state in states[] array is the starting state. rules like "it can have no incoming transitions" etc do not really work as then they make the starting state not be able to be transitioned to again during workflow exec.

**Comment by cdavernas** [comment]
@tsurdilo sounds fine to me, it's not a big deal to implement and it was uselessly repetitive to specify the start param.

**Review by ricardozanini — APPROVED** [review]

**Review by tsurdilo — APPROVED** [review]

**Pull request merged**
