### PR TITLE
Fix workflow schema: change `const`, adding missing `object`; etc.

### PR DESCRIPTION
**Pull request by matthias-pichler-warrify**
Signed-off-by: Matthias Pichler <m.pichler@warrify.com>

**Please specify parts of this PR update:**

- [ ] Specification
- [x] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Use Cases
- [ ] Community
- [ ] CTK
- [ ] Other

**Discussion or Issue link**:

**What this PR does**:

I adressed some issues with the workflow schema:

1. I used `const` instead of `constant` as described here: https://json-schema.org/understanding-json-schema/reference/const
2. I added some missing `type: object` directives that made the schema fail certain strict schema checks (specifically ajv complained about the use of `properties` without `type: object`)
3. I allowed tasks to reference authentication policies defined under `use` by allowing string values for `authentication` fields of tasks
4. I replaced one erroneous use of `ref` with the correct `$ref`

**Additional information:**

the schema is very inconsistently formatted: would it be okay for me to configure `yamllint` and format the schema (in a separate PR?)

### CODE REVIEW

**Review by cdavernas — APPROVED** [review]
LGTM! Many thanks! ❤️

**Comment by ricardozanini** [comment]
> the schema is very inconsistently formatted: would it be okay for me to configure yamllint and format the schema (in a separate PR?)

@matthias-pichler-warrify please do! 🙏 

Can you also please add a GHA to validate if the YAML is formatted corrected? Also, I think we have a `vscode` configuration file that we can use for Contributors to configure their local dev.

So please, don't forget to add a section in CONTRIBUTIONS.md about how to lint. <3

**Review by ricardozanini — COMMENTED** [review]
Can you please add examples that validate these changes? 🙏

**Comment by matthias-pichler-warrify** [comment]
> > the schema is very inconsistently formatted: would it be okay for me to configure yamllint and format the schema (in a separate PR?)
> 
> @matthias-pichler-warrify please do! 🙏
> 
> Can you also please add a GHA to validate if the YAML is formatted corrected? Also, I think we have a `vscode` configuration file that we can use for Contributors to configure their local dev.
> 
> So please, don't forget to add a section in CONTRIBUTIONS.md about how to lint. <3

will do it separately though

**Comment by matthias-pichler-warrify** [comment]
> Can you please add examples that validate these changes? 🙏

I added examples to validate the last two points ... the first two are a matter of the schema itself so a different validation would have to be added.

**Review by ricardozanini — APPROVED** [review]

**Comment by matthias-pichler-warrify** [comment]
> > the schema is very inconsistently formatted: would it be okay for me to configure yamllint and format the schema (in a separate PR?)
> 
> @matthias-pichler-warrify please do! 🙏
> 
> Can you also please add a GHA to validate if the YAML is formatted corrected? Also, I think we have a `vscode` configuration file that we can use for Contributors to configure their local dev.
> 
> So please, don't forget to add a section in CONTRIBUTIONS.md about how to lint. <3

working on this here: https://github.com/serverlessworkflow/specification/pull/883/

**Pull request merged**
