### PR TITLE
change: documentation fix bearer.token property

### PR DESCRIPTION
**Pull request by matthias-pichler-warrify**
change: documentation

**Please specify parts of this PR update:**

- [x] Specification
- [ ] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Use Cases
- [ ] Community
- [ ] CTK
- [ ] Other

**Discussion or Issue link**:

**What this PR does**:

fixes the `token` property inside the `bearer` authentication being accidentally referred to as `bearer` as well

**Additional information:**

### CODE REVIEW

**Review by cdavernas — APPROVED** [review]
LGTM! Thanks!

**Review by ricardozanini — APPROVED** [review]

**Comment by matthias-pichler-warrify** [comment]
> @matthias-pichler-warrify if I may ask, can you add an example to the `examples/` directory validating this fix?

I added an example and updated some more typos I found in the Authentication section

**Review by fjtirado — APPROVED** [review]

**Review by cdavernas — APPROVED** [review]
LGTM! Cheers!

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
@cdavernas there was error in the CI, we shouldn't have merged it.

**Comment by matthias-pichler-warrify** [comment]
> @cdavernas there was error in the CI, we shouldn't have merged it.

You are right: a string with an interpolated variable such as `{petId}` does not match the `uri` format ... @ricardozanini should I: 
1. remove the interpolation
2. update the schema to no longer require the `uri` format?

**Comment by cdavernas** [comment]
> @cdavernas there was error in the CI, we shouldn't have merged it.

Damn! I thought it was still the expected "initial" schema bugs we had, sorry guys!

**Comment by cdavernas** [comment]
> update the schema to no longer require the uri format?

Update the schema so that it supports uri with `{ }` characters. A Regex might do the trick.

**Comment by matthias-pichler-warrify** [comment]
https://github.com/serverlessworkflow/specification/pull/880

**Comment by ricardozanini** [comment]
Just to have it documented, we fixed in #879

**Pull request merged**
