### PR TITLE
Data input/output schema update

### PR DESCRIPTION
**Pull request by tsurdilo**
Signed-off-by: Tihomir Surdilovic <tsurdilo@redhat.com>

**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ x] Specification
- [ x] Schema
- [ ] Examples
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [ ] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:
Updates the data schema input/output definitions
**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]
Much better this way. Thanks!

**Comment by manuelstein** [comment]
Existing parameter names are long, so I see grouping is nice. They could be renamed schemaInput/schemaOutput or inputSchema/outputSchema. But I guess this is up to taste. Grouping also adds a level.

I think we should add clarification on the filtering. Currently, input only validates and output seems to both validate and scrub, but I can see where scrubbing might be useful on input. What happens if the schema fails to match (is there a named error)? Are additional JSON object parameters on input data kept (optional), cut (filtered) or does it not match if there's more data?

**Comment by tsurdilo** [comment]
@manuelstein good questions and btw this was requested via issue: https://github.com/serverlessworkflow/specification/issues/213

We will update all of this stuff once we decide what to do with expressions (using jq? jmespath? other?). For now this is just 
syntax update that is not update to functionality. There will be overarching updates on all this once this big question is clarified...dont worry :)

**Comment by tsurdilo** [comment]
rebased

**Pull request merged**
