### PR TITLE
Adding Ricardo Zanini to list of project maintainers

### PR DESCRIPTION
**Pull request by tsurdilo**
Signed-off-by: Tihomir Surdilovic <tsurdilo@redhat.com>

**Many thanks for submitting your Pull Request :heart:!**

**Please specify parts this PR updates:**

- [ ] Specification
- [ ] Schema
- [ ] Examples
- [ ] Usecases
- [ ] Extensions
- [ ] Roadmap
- [ ] Use Cases
- [x] Community
- [ ] TCK
- [ ] Other

**What this PR does / why we need it**:
Project maintainers have voted to add  Ricardo Zanini to the list of project maintainers. There was no objections. Congrats Zanini
**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Review by ricardozanini — APPROVED** [review]

**Comment by tsurdilo** [comment]
@manuelstein waiting on your +1 to merge :)

**Review by manuelstein — APPROVED** [review]
LGTM

**Comment by manuelstein** [comment]
> @manuelstein waiting on your +1 to merge :)

Sorry, was confused by the file moving from community/maintainers.md to MAINTAINERS.md

**Comment by tsurdilo** [comment]
@manuelstein yeah I noticed we had two files with maintainers info. Probably need just one, so I removed the old one.

**Comment by tsurdilo** [comment]
@manuelstein i think cncf uses the MAINTAINERS.md to pull names for each project to set up mailing lists etc. So that one we need to keep.

**Comment by tsurdilo** [comment]
forgot to update the owners doc. revised

**Pull request merged**
